#!/usr/bin/env ansible-playbook
---

- name: Defines YAML macros
  hosts: localhost
  gather_facts: False
  vars:
    macros:
      - &ro
        changed_when: False
        check_mode: False
      - &lo
        delegate_to: localhost
        run_once: True
      - &rolo
        <<: *ro
        <<: *lo
    constants:
      - &common
        private_repos_file: private-repos.yml

- name: Assertions
  hosts: all
  gather_facts: False
  run_once: True
  tags: always
  vars: { <<: *common }
  tasks:
    - <<: *lo
      block:
      - assert:
          that: running_ansible_version is version(local_min_ansible_version, '>=')
          fail_msg: min ansible version is {{ local_min_ansible_version }}, ansible version is {{ running_ansible_version }}
        vars:
          default_min_ansible_version: 2.7
          running_ansible_version: '{{ ansible_version.major ~ "." ~ ansible_version.minor }}'
          local_min_ansible_version: '{{ min_ansible_version | default(default_min_ansible_version) }}'
        name: Assert {{ running_ansible_version }} >= {{ local_min_ansible_version }}
      - stat: { path: '{{ file }}' }
        vars: &prf { file: '{{ private_repos_file }}' }
        register: st
        name: Stat {{ file }}
      - assert:
          that: st.stat.exists
          fail_msg: |
            Create a {{ file }} file to define
            - password_store_repo
            - gpg_store_repo
        vars: *prf
        name: Assert {{ file }}
      vars: &assert { assertions: '{{ not no_assert | default(False) }}' }
      when: assertions
      name: Ansible version and {{ private_repos_file }}

- name: Assertions
  hosts: all
  gather_facts: False
  run_once: True
  tags: always
  tasks:
    - <<: *lo
      block:

      - <<: *ro
        command: ssh-add -l
        register: ssh_add
        name: Get cached ssh keys
      - assert:
          that: ssh_add.rc == 0
          fail_msg: Empty ssh agent
        name: Assert we have cached ssh keys

      - git_config:
          name: user.email
          repo: .
          scope: local
        register: git_config
        name: Get user email from git config
      - <<: *ro
        name: Get keygrip of GPG key using email ID
        command: gpg2 --fingerprint --with-keygrip '<{{ git_config.config_value }}>'
        register: gpg_keygrip
      - assert:
          that: gpg_keygrip.rc == 0
          fail_msg: '{{ gpg_keygrip.stderr }}'
        name: Assert keygrip
      - <<: *ro
        name: Get gpg-agent cache status for GPG passphrase 
        command: gpg-connect-agent
        register: gpg_connect_agent
        args:
          stdin: keyinfo {{ gpg_keygrip.stdout_lines[-1].split()[-1] }}
      - assert:
          that: gpg_connect_agent.stdout_lines[0].split()[6]|int == 1
          fail_msg: passphrase for {{ git_config.config_value }} uncached

      vars: { <<: *assert, agent_check: '{{ not no_agent_check | default(False) }}' }
      when: agent_check and assertions
      name: Check ssh and gpg agent

- hosts: all
  gather_facts: False

  vars:
    <<: *common
    workdir: ext
    password_store_git: '{{ workdir }}/infra-password-store'
    password_store_dir: '{{ playbook_dir }}/{{ workdir }}/infra-password-store/password-store' # passwordstore lookup needs full path
    gnupg_repo: '{{ workdir }}/infra-gpg-store'
    gnupg_user: '{{ user | default("duplicity") }}'
    gnupg_homedir: '{{ gnupg_repo }}/{{ gnupg_user }}/.gnupg'
    gnupg_keysdir: '{{ gnupg_repo }}/{{ gnupg_user }}/keys'

  vars_files: [ '{{ private_repos_file }}' ]

  tasks:

    - set_fact:
        keys:
          - id_epiconcept
          - t.delamare@epiconcept.fr
      name: Choice of ssh key

    - set_fact:
        git_ssh_key_file: |-
          {{ lookup('env', 'GIT_SSH_KEY_FILE') | default('~/.ssh/' ~ keys[1], True) }}
      name: Define git_ssh_key_file

    - file:
        path: '{{ workdir }}'
        state: directory
      <<: *lo
      name: Create {{ workdir }}

    - git:
        repo: '{{ password_store_repo }}'
        dest: &password_store '{{ password_store_git }}'
        key_file: '{{ git_ssh_key_file }}'
      <<: *lo
      tags: clone
      name: Get password store repo

    - git:
        repo: '{{ gpg_store_repo }}'
        dest: &gpg_store '{{ gnupg_repo }}'
        key_file: '{{ git_ssh_key_file }}'
      <<: *lo
      tags: clone
      name: Get gpg store repo

    - git_config:
        repo: '{{ item }}'
        name: core.sshCommand
        scope: local
        value: ssh -i {{ git_ssh_key_file }} -F /dev/null
      <<: *lo
      loop: [ *password_store, *gpg_store ]
      name: Configure core.sshCommand

    - set_fact: { email: '{{ gnupg_user }}@{{ inventory_hostname }}' }
      name: Define email
      tags: always

    - set_fact: { password: '{{ gnupg_user }}/{{ email }} create=true directory={{ password_store_dir }}' }
      name: Define passwordstore invocation

    - set_fact:
        passphrase: |-
          {{ lookup('passwordstore', password) }}
      name: Generate new password

    - meta: noop
      vars:
        macros:
          - &pass
            environment:
              PASSWORD_STORE_GIT: '{{ password_store_git }}'
              PASSWORD_STORE_DIR: '{{ password_store_dir }}'
              GIT_SSH_COMMAND: 'ssh -i {{ git_ssh_key_file }}'
            delegate_to: localhost

    - command: pass git rev-parse @
      <<: *pass
      <<: *ro
      register: head
      name: Get head

    - command: pass git rev-parse @{u}
      <<: *pass
      <<: *ro
      register: upstream
      name: Get upstream

    - command: pass git push
      <<: *pass
      when: head.stdout != upstream.stdout
      name: Push new password

    - file:
        path: '{{ item }}'
        state: directory
        mode: 0700
      loop: [ '{{ gnupg_homedir }}', '{{ gnupg_keysdir }}' ]
      <<: *lo
      name: Create GPG dirs

    - &check
      command:
      args:
        argv:
          - gpg2
          - --homedir
          - '{{ gnupg_homedir }}'
          - --list-secret-keys
          - '<{{ email }}>'
      delegate_to: localhost
      register: gpg
      failed_when: gpg.rc > 2
      <<: *ro
      name: Check GPG key

    - copy:
        content: |
          Key-Type: default
          Subkey-Type: default
          Name-Real: {{ gnupg_user }}
          Name-Comment: for {{ inventory_hostname }}
          Name-Email: {{ email }}
          Expire-Date: 0
          Passphrase: {{ passphrase }}
          %commit
          %echo done
        dest: &script '{{ workdir }}/{{ inventory_hostname }}.script'
      no_log: True
      delegate_to: localhost
      when: gpg.rc == 2
      name: Generate gpg script

    - command:
      args:
        argv:
          - gpg2
          - --homedir
          - '{{ gnupg_homedir }}'
          - --batch
          - --generate-key
          - *script
      delegate_to: localhost
      when: gpg.rc == 2
      name: Generate GPG key

    - *check # listing new keys changes trustdb

    - file:
        path: *script
        state: absent
      delegate_to: localhost
      name: Delete gpg script

    - command:
      args:
        argv:
          - gpg2
          - --homedir
          - '{{ gnupg_homedir }}'
          - --armor
          - --export
          - --output
          - &src_key_asc '{{ gnupg_keysdir }}/{{ email }}.asc'
          - '{{ email }}'
        creates: *src_key_asc
      delegate_to: localhost
      name: Export pub key
      tags: export

    - set_fact:
        src_key_priv: &src_key_priv '{{ gnupg_keysdir }}/{{ email }}.priv'
        key_priv_pass: '{{ gnupg_user }}/{{ email }} directory={{ password_store_dir }}'
      name: Define src_key_priv and passwordstore invocation

    - expect:
        command: gpg2 --homedir {{ gnupg_homedir }} --export-secret-keys --armor --output {{ src_key_priv }}
        responses:
          (?i)Passphrase: |
            {{ lookup('passwordstore', key_priv_pass) }}
        creates: *src_key_priv
      no_log: True
      <<: *lo
      name: Export priv key

    - <<: *ro
      command: git -C {{ gnupg_repo }} status --porcelain
      delegate_to: localhost
      register: status
      name: Get status

    - command: git -C {{ gnupg_repo }} {{ item }}
      delegate_to: localhost
      when: status.stdout_lines|length|int
      with_items:
        - add .
        - commit -m 'Adds {{ email }} via ansible'
      name: Add GPG key

    - <<: *ro
      command: git -C {{ gnupg_repo }} rev-parse {{ item }}
      delegate_to: localhost
      register: head_upstream
      with_items: [ '@', '@{u}' ]
      name: Get head and upstream

    - command: git -C {{ gnupg_repo }} push
      environment:
        GIT_SSH_COMMAND: 'ssh -i {{ git_ssh_key_file }}'
      delegate_to: localhost
      when: head_upstream.results[0].stdout != head_upstream.results[1].stdout
      name: Push new key

    - copy:
        src: *src_key_asc
        dest: &dst_key_asc /etc/duplicity/{{ email }}.asc
      become: True
      name: Copy pub key
      tags: export

    - command: gpg2 --list-keys '<{{ email }}>'
      become: True
      register: gpg
      failed_when: gpg.rc > 2
      <<: *ro
      name: Check GPG key imported
      tags: export

    - command:
      args: { argv: [ gpg2, --import, *dst_key_asc ] }
      become: True
      when: gpg.rc == 2
      name: Import GPG key
      tags: export

    - command:
      args:
        argv: [ gpg2, --no-tty, --command-fd, 0, --edit-key, '<{{ email }}>' ]
        stdin: "trust\n5\ny"
      become: True
      when: gpg.rc == 2
      name: Trust GPG key
      tags: export

    - meta: end_play
      tags: always
